FROM golang:1.25-alpine

# Instalar dependencias del sistema necesarias y actualizar paquetes base
RUN apk upgrade --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main busybox alpine-baselayout apk-tools && apk add --no-cache bash git ca-certificates tzdata

WORKDIR /go/src/github.com/mario-ezquerro/registrator/

# Ya no necesitamos descargar dependencias online porque usaremos la carpeta /vendor local
COPY . .

# Compilar para entorno de desarrollo (con la carpeta local vendor)
RUN go build -mod=vendor -ldflags "-X main.Version=$(cat VERSION)-dev" -o /bin/registrator .

CMD ["/bin/registrator"]
