FROM golang:1.22-alpine3.20 AS builder

# Establece el directorio de trabajo al nuevo path del módulo
WORKDIR /go/src/github.com/mario-ezquerro/registrator/

COPY . /go/src/github.com/mario-ezquerro/registrator

# Instala git (necesario para que Go obtenga módulos que no están en el proxy o usan git para versiones)
# y ca-certificates (para conexiones HTTPS).
# Compila la aplicación Go.
# CGO_ENABLED=0 para un binario estático.
# -ldflags para establecer la versión.
# Salida a /bin/registrator.
RUN apk add --no-cache git ca-certificates \
	&& apk --no-cache add ca-certificates \
	&& CGO_ENABLED=0 GOOS=linux go build \
		-ldflags "-X main.Version=dev" \
		-o /bin/registrator .

CMD ["/bin/registrator"]
